export const projects = [
  {
    slug: 'shopsphere',
    number: '01',
    title: 'ShopSphere — E-Commerce Microservices',
    tagline: 'Production-oriented e-commerce backend built with .NET Microservices, Redis, RabbitMQ & JWT',
    description:
      'ShopSphere is a production-oriented e-commerce backend built using .NET Microservices architecture. The system is designed with independent services for authentication, products, cart, inventory, orders, payments, notifications, and reviews, with separate databases for service-level data ownership. It uses JWT-based authentication, refresh tokens, Redis for caching, and RabbitMQ for asynchronous event-driven communication between services. The project focuses on clean API design, scalability, security, fault isolation, and real-world backend architecture. AI-powered features such as an intelligent shopping assistant and semantic product search are planned as a future extension.',
    image: '/images/project-product-catalog.png',
    tags: ['.NET Core', 'Microservices', 'RabbitMQ', 'Redis', 'JWT Auth', 'Docker', 'REST API'],
    overview:
      'ShopSphere is an enterprise-grade, distributed e-commerce backend engineered using .NET Microservices principles. Each core domain — Authentication, Product Catalog, Shopping Cart, Inventory, Orders, Payments, Notifications, and Reviews — functions as an autonomous service with isolated database storage. Inter-service coordination relies on RabbitMQ message broker for event publishing and Redis for distributed caching, providing ultra-low latency and resilient fault tolerance.',
    features: [
      'Independent domain microservices: Auth, Catalog, Cart, Inventory, Orders, Payments, Notifications, Reviews',
      'Service-level database ownership ensuring strict domain boundary and fault isolation',
      'Stateless JWT authentication paired with rotating refresh token lifecycle',
      'Redis distributed caching for high-speed catalog lookup and cart sessions',
      'Asynchronous event-driven messaging with RabbitMQ for order processing and notifications',
      'Resilient circuit breaker & retry policies on inter-service HTTP/gRPC pipelines',
      'Role-based access controls (RBAC) across customer, vendor, and administrator personas',
      'Docker containerization and orchestration readiness for cloud microservices',
      'Planned AI extension: Intelligent shopping assistant and semantic vector product search',
    ],
    architecture: [
      { label: 'API Gateway & Routing', detail: 'Centralized entry point managing rate limiting, SSL termination, and microservice routing' },
      { label: 'Authentication Service', detail: '.NET service issuing JWT access tokens and managing secure refresh token persistence' },
      { label: 'Domain Microservices', detail: 'Autonomous Services: Products, Cart, Inventory, Orders, Payments, Reviews' },
      { label: 'Event Message Broker', detail: 'RabbitMQ handling asynchronous pub/sub events for order checkout, stock updates, and alerts' },
      { label: 'Distributed Cache', detail: 'Redis in-memory caching cluster for instant product querying and session state' },
      { label: 'Data Layer', detail: 'Dedicated databases per service guaranteeing true data ownership and zero coupling' },
    ],
    stack: [
      { group: 'Architecture', items: ['.NET Core', 'Microservices', 'Clean Architecture', 'Event-Driven', 'Docker'] },
      { group: 'Messaging & Cache', items: ['RabbitMQ', 'Redis', 'MassTransit', 'REST API'] },
      { group: 'Security & Storage', items: ['JWT & Refresh Tokens', 'SQL Server / PostgreSQL', 'MongoDB', 'RBAC'] },
    ],
    security: [
      'Zero-trust microservice communication with scoped JWT bearer validation',
      'Secure refresh token rotation preventing token hijacking and replay attacks',
      'Isolated database connection credentials with strict principle of least privilege',
      'Rate limiting and distributed DDoS protection at API Gateway entry points',
      'Strict input sanitization and payload validation across all service endpoints',
    ],
  },
  {
    slug: 'product-catalog-management',
    number: '02',
    title: 'Product Catalog Management System',
    tagline: 'Full-stack product management platform with secure JWT authentication and granular controls',
    description:
      'A full-stack product management application built using React.js, Node.js, Express.js, and MongoDB. The system provides secure authentication and allows users to manage products through protected CRUD operations, search, filtering, validation, and pagination.',
    image: '/images/project-product-catalog.png',
    tags: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'JWT', 'REST API'],
    overview:
      'A robust full-stack solution built to streamline product catalog operations for retail and e-commerce inventories. The system enforces secure JWT authentication and password hashing with bcrypt, enabling authorized administrators to effortlessly create, update, search, filter, and paginate products across large catalogs.',
    features: [
      'User Registration & Login with secure password hashing (bcrypt)',
      'JWT-based Authentication & protected routes',
      'Protected product management with full CRUD operations',
      'Instant keyword search across product inventory',
      'Multi-category filtering and sorting',
      'Server-side & client-side pagination controls',
      'Comprehensive product schema validation',
      'RESTful API architecture with Axios client integration',
      'Responsive, modern UI built with React.js & Bootstrap',
      'MongoDB database integration with Mongoose ODM',
    ],
    architecture: [
      { label: 'Client Layer', detail: 'React.js single page application with Bootstrap styling and responsive layouts' },
      { label: 'Network Client', detail: 'Axios HTTP instance configured with JWT request/response interceptors' },
      { label: 'REST API', detail: 'Express.js routers providing versioned endpoints for auth and catalog CRUD' },
      { label: 'Security & Auth', detail: 'JWT bearer verification middleware, bcrypt salt rounds password encryption' },
      { label: 'Data Model', detail: 'Mongoose schemas with field validations, search indexes, and pagination plugins' },
      { label: 'Database', detail: 'MongoDB document database for scalable catalog storage' },
    ],
    stack: [
      { group: 'Frontend', items: ['React.js', 'JavaScript', 'Bootstrap', 'CSS', 'Axios'] },
      { group: 'Backend', items: ['Node.js', 'Express.js', 'REST API', 'JWT', 'bcrypt'] },
      { group: 'Database', items: ['MongoDB', 'Mongoose'] },
    ],
    security: [
      'JWT-based stateless authentication with token verification middleware',
      'Secure password hashing with bcrypt using salt hashing rounds',
      'Protected API route guards preventing unauthorized CRUD operations',
      'Strict input validation and payload sanitization on all endpoints',
      'Secure HTTP headers and CORS configuration',
    ],
    video: {
      url: '/videos/product-catalog.mp4',
      thumbnail: '/images/project-product-catalog.png',
      duration: '2:15',
      durationSeconds: 135,
      resolution: '1080p 60fps',
      urlDisplay: 'catalog-management.internal/demo-walkthrough',
      title: 'Product Catalog System Demo',
      description:
        'Complete end-to-end walkthrough covering secure admin authentication, JWT session persistence, instant CRUD operations, debounced catalog search, category filtering, and responsive data grid.',
      highlights: [
        'Secure JWT login flow and protected route access guards',
        'Real-time product creation with schema validation & price checks',
        'Debounced search across catalog titles and descriptions',
        'Instant multi-category filtering and responsive table cards',
      ],
      chapters: [
        { time: '0:00', seconds: 0, title: 'Auth & Login Session' },
        { time: '0:35', seconds: 35, title: 'Product Creation & Validation' },
        { time: '1:10', seconds: 70, title: 'Debounced Search & Filtering' },
        { time: '1:45', seconds: 105, title: 'Inline Edit & Delete Actions' },
      ],
    },
  },
  {
    slug: 'expense-tracker',
    number: '03',
    title: 'Expense Tracker',
    tagline: 'Responsive expense management app with categorization, validation, and amount tracking',
    description:
      'A responsive expense management application built with React.js that allows users to add, edit, delete, and manage their expenses efficiently. The application includes form validation, expense categorization, amount tracking, and date-based expense records.',
    image: '/images/project-expense-tracker.png',
    tags: ['React.js', 'JavaScript', 'Bootstrap', 'CSS', 'Node.js', 'REST API'],
    overview:
      'A clean, responsive expense management web application crafted with React.js and backed by REST APIs. It provides an intuitive interface for individuals to take control of their personal finance through real-time amount tracking, categorized spending logs, flexible date filters, and robust form validation.',
    features: [
      'Add new expense entries with category, amount, date, and notes',
      'Edit existing expenses with live preview updates',
      'Delete expenses with prompt confirmations',
      'Dynamic expense categorization (Food, Travel, Utilities, Subscriptions, etc.)',
      'Real-time spending balance and cumulative amount tracking',
      'Date-based expense logs and time-range filtering',
      'Client-side form validation for clean data integrity',
      'Responsive design styled with Bootstrap and custom CSS',
      'REST API integration using Axios for persistent records',
    ],
    architecture: [
      { label: 'UI Interface', detail: 'React component tree with interactive dashboard cards and transaction lists' },
      { label: 'State Management', detail: 'React hooks for local form validation, filtering, and live balance totals' },
      { label: 'Data Communication', detail: 'Axios service layer communicating with RESTful backend endpoints' },
      { label: 'Backend Service', detail: 'Node.js REST API handling expense validation, queries, and mutations' },
      { label: 'Styling Layer', detail: 'Custom dark luxury CSS variables paired with Bootstrap grid structure' },
    ],
    stack: [
      { group: 'Frontend', items: ['React.js', 'JavaScript', 'Bootstrap', 'CSS'] },
      { group: 'Backend', items: ['Node.js', 'REST API', 'Axios'] },
      { group: 'Tools', items: ['Form Validation', 'Date Fmt', 'Git'] },
    ],
    security: [
      'Rigorous client and server validation on amount formats and category enums',
      'Sanitized payload inputs preventing cross-site scripting (XSS)',
      'Defensive error boundaries to ensure smooth UI fallback during network failures',
    ],
    video: {
      url: '/videos/expense-tracker.mp4',
      thumbnail: '/images/project-expense-tracker.png',
      duration: '1:45',
      durationSeconds: 105,
      resolution: '1080p 60fps',
      urlDisplay: 'expense-tracker.local/live-walkthrough',
      title: 'Expense Tracker Interactive Demo',
      description:
        'Comprehensive live demonstration showing dynamic expense entry, instant category filtering, real-time balance calculations, form validation safeguards, and responsive mobile layouts.',
      highlights: [
        'Instant balance sum calculation and real-time total updates',
        'Dynamic categorization across Food, Travel, Shopping, and Utilities',
        'Strict validation rules preventing negative values or blank submissions',
        'Interactive edit, deletion, and reactive state synchronization',
      ],
      chapters: [
        { time: '0:00', seconds: 0, title: 'Dashboard Overview & Balance' },
        { time: '0:28', seconds: 28, title: 'Adding Categorized Expense' },
        { time: '0:55', seconds: 55, title: 'Category Filtering' },
        { time: '1:20', seconds: 80, title: 'Edit, Delete & State Sync' },
      ],
    },
  },
  {
    slug: 'devtask-reminder',
    number: '04',
    title: 'DevTask Reminder App',
    tagline: 'A focused task and reminder system built for developers',
    description:
      'A task manager designed around developer workflows — recurring reminders, priority queues and a REST API that any client can consume.',
    image: '/images/project-devtask.png',
    tags: ['.NET', 'REST API', 'JavaScript', 'MongoDB'],
    overview:
      'General task apps do not fit the way developers actually work. DevTask keeps a flat, keyboard-driven list, supports recurring technical chores, and exposes everything through a REST API so reminders can be triggered from scripts or CI as easily as from the UI.',
    features: [
      'Task creation with priority, tags and due windows',
      'Recurring reminders for repeating engineering chores',
      'Notification queue with snooze and reschedule',
      'Keyboard-first interaction across the whole app',
      'REST API for programmatic task creation',
      'Daily digest of what is due and what slipped',
    ],
    architecture: [
      { label: 'Client', detail: 'Browser UI and external scripts' },
      { label: 'Frontend', detail: 'Vanilla JavaScript, fetch, optimistic updates' },
      { label: 'REST API', detail: '.NET endpoints with DTO validation' },
      { label: 'Authentication', detail: 'JWT tokens with per-user scoping' },
      { label: 'Business Logic', detail: 'Scheduling service, recurrence engine' },
      { label: 'Database', detail: 'MongoDB documents for flexible task shapes' },
    ],
    stack: [
      { group: 'Backend', items: ['C#', '.NET', 'REST API', 'JWT'] },
      { group: 'Database', items: ['MongoDB'] },
      { group: 'Frontend', items: ['HTML', 'CSS', 'JavaScript'] },
    ],
    security: [
      'Per-user scoping on every query and mutation',
      'JWT authentication for both UI and script clients',
      'Input validation and payload size limits',
      'Rate limiting on the public task creation endpoint',
    ],
  },
]

export function getProject(slug) {
  return projects.find((p) => p.slug === slug)
}
